version: "3.8"
name: soyhuce_skander_boudawara_exercice
services:
  postgres_soyhuce:
    image: "postgres:14.8"
    container_name: postgres_soyhuce
    # automatically restarts the container - Docker daemon on restart or 
    # the container itself is manually restarted
    restart: always 
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: soyhuce
      POSTGRES_DB: soyhuce_db
    ports:
      - "5432:5432" 
    networks:
      project_soyhuce:
        ipv4_address: "192.168.92.22"
  pgadmin_soyhuce:
    # Image of the second service to launch
    container_name: pgadmin4_soyhuce
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres_soyhuce
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@soyhuce.com
      PGADMIN_DEFAULT_PASSWORD: soyhuce
      PGADMIN_CONFIG_MASTER_PASSWORD_REQURED: "False"
      # PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./configuration/pgadmin:/var/lib/pgadmin
    networks:
      project_soyhuce:
        ipv4_address: "192.168.92.21"
  python_soyhuce:
    container_name: python_soyhuce
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
     - pgadmin_soyhuce
    env_file:
      - .env
    tty: true
    volumes:
     - ./transform:/app
    networks:
      project_soyhuce:
        ipv4_address: "192.168.92.23"
    ports:
      - "8050:8050"
    command: python /app/dahsboard.py
networks:
  project_soyhuce:
    ipam:
      driver: default
      config:
        - subnet: "192.168.92.0/24"
          gateway: "192.168.92.1"